# coding: utf-8

"""
    Barte Api

    Documentação para integração com a API da Barte <h3>Segurança</h3> Utilizamos um token de autorização cadastrado dentro da plataforma da Barte no menu  <b>Configurações -> Integração -> Chaves API</b> para autenticar as operações executadas.</br> Adicione o token a requisição utilizando o header <b>X-Token-Api</b>, na documentação utilize  o botão <b>Authorize</b> para os testes. <h3>Ambientes</h3> Disponibilizamos dois ambientes <b>(sandbox e produção)</b>. Utilize o primeiro para seus  testes de desenvolvimento.</br> Você pode selecionar o ambiente que quer utilizar na nossa documentação através com combo  <b>servers</b></br> <b>Observação: </b> Entre contato com nossa equipe de operações para lhe auxiliar na criação  de uma conta em nosso ambiente de sandbox.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bartesdk.api.apide_pedidos_work_in_progress_api import APIDePedidosWorkInProgressApi


class TestAPIDePedidosWorkInProgressApi(unittest.TestCase):
    """APIDePedidosWorkInProgressApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIDePedidosWorkInProgressApi()

    def tearDown(self) -> None:
        pass

    def test_cancel1(self) -> None:
        """Test case for cancel1

        Cancela um pedido pelo seu ID.
        """
        pass

    def test_create2(self) -> None:
        """Test case for create2

        Cria um pedido
        """
        pass

    def test_find_all1(self) -> None:
        """Test case for find_all1

        Busca todas os pedidos do usuário logado.
        """
        pass

    def test_find_by_uuid1(self) -> None:
        """Test case for find_by_uuid1

        Busca um pedido pelo seu ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
