# coding: utf-8

"""
    Barte Api

    Documentação para integração com a API da Barte <h3>Segurança</h3> Utilizamos um token de autorização cadastrado dentro da plataforma da Barte no menu  <b>Configurações -> Integração -> Chaves API</b> para autenticar as operações executadas.</br> Adicione o token a requisição utilizando o header <b>X-Token-Api</b>, na documentação utilize  o botão <b>Authorize</b> para os testes. <h3>Ambientes</h3> Disponibilizamos dois ambientes <b>(sandbox e produção)</b>. Utilize o primeiro para seus  testes de desenvolvimento.</br> Você pode selecionar o ambiente que quer utilizar na nossa documentação através com combo  <b>servers</b></br> <b>Observação: </b> Entre contato com nossa equipe de operações para lhe auxiliar na criação  de uma conta em nosso ambiente de sandbox.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "bartesdk"
VERSION = "2.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Barte Api",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Barte Api"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Documentação para integração com a API da Barte &lt;h3&gt;Segurança&lt;/h3&gt; Utilizamos um token de autorização cadastrado dentro da plataforma da Barte no menu  &lt;b&gt;Configurações -&gt; Integração -&gt; Chaves API&lt;/b&gt; para autenticar as operações executadas.&lt;/br&gt; Adicione o token a requisição utilizando o header &lt;b&gt;X-Token-Api&lt;/b&gt;, na documentação utilize  o botão &lt;b&gt;Authorize&lt;/b&gt; para os testes. &lt;h3&gt;Ambientes&lt;/h3&gt; Disponibilizamos dois ambientes &lt;b&gt;(sandbox e produção)&lt;/b&gt;. Utilize o primeiro para seus  testes de desenvolvimento.&lt;/br&gt; Você pode selecionar o ambiente que quer utilizar na nossa documentação através com combo  &lt;b&gt;servers&lt;/b&gt;&lt;/br&gt; &lt;b&gt;Observação: &lt;/b&gt; Entre contato com nossa equipe de operações para lhe auxiliar na criação  de uma conta em nosso ambiente de sandbox.
    """,  # noqa: E501
    package_data={"bartesdk": ["py.typed"]},
)
