name: SonarCloud Analysis

on:
  push:
    branches:
      - master  # ou master, dependendo do nome da sua branch principal
  pull_request:
    branches:
      - master  # ou master

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar análise do SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.organization=barte \
                        -Dsonar.projectKey=barte-sdk-python \
                        -Dsonar.host.url=https://sonarcloud.io
